'use client';

import React,{useEffect,useState} from 'react';
import {AdminShell} from '@/components/admin/AdminShell';
import {createClient} from '@/lib/supabase/client';

type Profile={id:string;full_name:string|null;email:string|null;role:string};
type Staff={id:string;user_id:string;branch_id:string|null;employee_code:string|null;job_title:string|null;is_active:boolean};
type Branch={id:string;name:string};

export default function AdminStaffPage(){const c=createClient();const [profiles,setProfiles]=useState<Profile[]>([]);const [staff,setStaff]=useState<Staff[]>([]);const [branches,setBranches]=useState<Branch[]>([]);const [userId,setUserId]=useState('');const [branchId,setBranchId]=useState('');const [jobTitle,setJobTitle]=useState('');const [employeeCode,setEmployeeCode]=useState('');const [editingId,setEditingId]=useState<string|null>(null);const [error,setError]=useState('');
 const load=async()=>{if(!c)return;const [a,b,d]=await Promise.all([c.from('profiles').select('id,full_name,email,role').order('full_name'),c.from('staff_profiles').select('*').order('created_at',{ascending:false}),c.from('branches').select('id,name').eq('is_active',true).order('name')]);if(a.error||b.error||d.error)setError(a.error?.message||b.error?.message||d.error?.message||'Unable to load staff');else{setProfiles((a.data||[]) as Profile[]);setStaff((b.data||[]) as Staff[]);setBranches((d.data||[]) as Branch[])}};useEffect(()=>{void load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!c||!userId)return;const payload={user_id:userId,branch_id:branchId||null,employee_code:employeeCode.trim()||null,job_title:jobTitle.trim()||null,is_active:true};const r=editingId?await c.from('staff_profiles').update(payload).eq('id',editingId):await c.from('staff_profiles').insert(payload);if(r.error)setError(r.error.message);else{setEditingId(null);setUserId('');setBranchId('');setJobTitle('');setEmployeeCode('');await load()}};
 return <AdminShell title="Staff & Technicians" subtitle="Assign staff profiles to users and branches for service operations."><div className="grid grid-cols-1 xl:grid-cols-12 gap-6"><form onSubmit={save} className="xl:col-span-5 bg-white border rounded-xl p-6 space-y-4"><h2 className="font-display font-bold">{editingId?"Edit Staff Profile":"Add Staff Profile"}</h2><select required value={userId} onChange={e=>setUserId(e.target.value)} className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"><option value="">Choose user</option>{profiles.filter(p=>(!editingId && !staff.some(s=>s.user_id===p.id)) || (editingId && p.id===userId)).map(p=><option key={p.id} value={p.id}>{p.full_name||p.email||p.id} {p.role==='admin'?'(admin)':''}</option>)}</select><select value={branchId} onChange={e=>setBranchId(e.target.value)} className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"><option value="">No branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><input value={employeeCode} onChange={e=>setEmployeeCode(e.target.value)} placeholder="Employee code" className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"/><input value={jobTitle} onChange={e=>setJobTitle(e.target.value)} placeholder="Job title" className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"/>{error&&<p className="text-xs text-red-700">{error}</p>}<div className="flex gap-2"><button className="flex-1 py-2.5 bg-[#141413] text-white rounded-lg text-xs font-semibold">{editingId?"Save Staff Profile":"Create Staff Profile"}</button>{editingId&&<button type="button" onClick={()=>{setEditingId(null);setUserId("");setBranchId("");setJobTitle("");setEmployeeCode("")}} className="px-4 py-2.5 border rounded-lg text-xs font-semibold">Cancel</button>}</div></form><section className="xl:col-span-7 bg-white border rounded-xl p-6"><h2 className="font-display font-bold mb-5">Staff Profiles ({staff.length})</h2><div className="space-y-3">{staff.map(s=>{const p=profiles.find(x=>x.id===s.user_id);const b=branches.find(x=>x.id===s.branch_id);return <div key={s.id} className="border rounded-lg p-4 flex justify-between gap-4"><div><p className="text-sm font-semibold">{p?.full_name||p?.email||s.user_id}</p><p className="text-xs text-[#6E6E68]">{s.job_title||'Staff'} · {b?.name||'No branch'} · {s.employee_code||'No code'}</p></div><div className="flex items-center gap-3 text-xs"><button onClick={()=>{setEditingId(s.id);setUserId(s.user_id);setBranchId(s.branch_id||"");setJobTitle(s.job_title||"");setEmployeeCode(s.employee_code||"");window.scrollTo({top:0,behavior:"smooth"})}} className="font-semibold hover:underline">Edit</button><button onClick={async()=>{if(!c)return;const r=await c.from('staff_profiles').update({is_active:!s.is_active}).eq('id',s.id);if(r.error)setError(r.error.message);else await load()}} className="text-xs font-semibold text-red-700">{s.is_active?'Deactivate':'Activate'}</button></div></div>})}</div></section></div></AdminShell>
}
