'use client';

import React, { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useStore } from '@/components/shared/StoreProvider';

export default function RegisterPage() {
 const router=useRouter(); const {register}=useStore();
 const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [phone,setPhone]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('');
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!name.trim()||!email.includes('@')||!phone.trim()||password.length<6){setError('Please complete all fields. Password must be at least 6 characters.');return;}setError('');if(await register(name,email,phone,password))router.push('/account');};
 return <div className="max-w-md mx-auto px-4 sm:px-8 py-16"><div className="bg-white border border-[#E5E5E0] rounded-xl p-7 sm:p-8 space-y-6"><div><p className="text-xs font-medium text-[#6E6E68]">NorthBros Garage Account</p><h1 className="font-display text-2xl font-bold text-[#141413]">Create Your Account</h1><p className="text-xs text-[#6E6E68]">Save parts, track orders, manage your shipping details, and book workshop services.</p></div><form onSubmit={submit} className="space-y-4"><div><label className="block text-xs font-semibold mb-1">Full Name</label><input required value={name} onChange={e=>setName(e.target.value)} className="w-full px-3.5 py-2.5 text-sm bg-[#FAF9F6] border border-[#E5E5E0] rounded-lg"/></div><div><label className="block text-xs font-semibold mb-1">Email Address</label><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} className="w-full px-3.5 py-2.5 text-sm bg-[#FAF9F6] border border-[#E5E5E0] rounded-lg"/></div><div><label className="block text-xs font-semibold mb-1">Mobile Number</label><input required type="tel" value={phone} onChange={e=>setPhone(e.target.value)} className="w-full px-3.5 py-2.5 text-sm bg-[#FAF9F6] border border-[#E5E5E0] rounded-lg"/></div><div><label className="block text-xs font-semibold mb-1">Password</label><input required type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="w-full px-3.5 py-2.5 text-sm bg-[#FAF9F6] border border-[#E5E5E0] rounded-lg"/></div>{error&&<p className="text-xs text-red-700">{error}</p>}<button type="submit" className="w-full py-2.5 bg-[#141413] text-white text-xs font-semibold rounded-lg">Create Account</button></form><div className="pt-4 border-t border-[#E5E5E0] flex items-center justify-between text-xs text-[#6E6E68]"><span>Already have an account?</span><Link href="/auth/login" className="font-semibold text-[#141413] hover:underline">Sign In →</Link></div></div></div>;
}
