'use client';

import React,{useEffect,useState} from 'react';
import {AdminShell} from '@/components/admin/AdminShell';
import {createClient} from '@/lib/supabase/client';
import {formatDate} from '@/lib/utils/format';

type Option={id:string;name:string;is_active?:boolean};
type Slot={id:string;branch_id:string;service_id:string;staff_id:string|null;start_time:string;end_time:string;capacity:number;is_available:boolean};

export default function AdminServiceSlotsPage(){
 const c=createClient();
 const [slots,setSlots]=useState<Slot[]>([]);const [branches,setBranches]=useState<Option[]>([]);const [services,setServices]=useState<Option[]>([]);const [staff,setStaff]=useState<Array<Option&{user_id:string}>>([]);const [branchId,setBranchId]=useState('');const [serviceId,setServiceId]=useState('');const [staffId,setStaffId]=useState('');const [start,setStart]=useState('');const [end,setEnd]=useState('');const [capacity,setCapacity]=useState('1');const [error,setError]=useState('');
 const load=async()=>{if(!c)return;const [a,b,d,e]=await Promise.all([c.from('service_slots').select('*').order('start_time',{ascending:true}),c.from('branches').select('id,name').eq('is_active',true).order('name'),c.from('services').select('id,name').eq('is_active',true).order('name'),c.from('staff_profiles').select('id,user_id,profiles(full_name)').eq('is_active',true).order('created_at')]);if(a.error||b.error||d.error||e.error)setError(a.error?.message||b.error?.message||d.error?.message||e.error?.message||'Unable to load slots');else{setSlots((a.data||[]) as Slot[]);setBranches((b.data||[]) as Option[]);setServices((d.data||[]) as Option[]);setStaff((e.data||[]).map((x:any)=>({id:x.id,user_id:x.user_id,name:x.profiles?.full_name||x.user_id})))}};
 useEffect(()=>{void load()},[]);
 const save=async(e:React.FormEvent)=>{e.preventDefault();if(!c||!branchId||!serviceId||!start||!end)return;const p={branch_id:branchId,service_id:serviceId,staff_id:staffId||null,start_time:new Date(start).toISOString(),end_time:new Date(end).toISOString(),capacity:Math.max(1,Number(capacity)||1),is_available:true};const r=await c.from('service_slots').insert(p);if(r.error)setError(r.error.message);else{setStart('');setEnd('');await load()}};
 return <AdminShell title="Service Availability & Slots" subtitle="Create the actual appointment windows used by the booking RPC."><div className="grid grid-cols-1 xl:grid-cols-12 gap-6"><form onSubmit={save} className="xl:col-span-5 bg-white border rounded-xl p-6 space-y-4"><h2 className="font-display font-bold">Create Availability Slot</h2><select required value={branchId} onChange={e=>setBranchId(e.target.value)} className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"><option value="">Choose branch</option>{branches.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select required value={serviceId} onChange={e=>setServiceId(e.target.value)} className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"><option value="">Choose service</option>{services.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select value={staffId} onChange={e=>setStaffId(e.target.value)} className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"><option value="">Any staff</option>{staff.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><div><label className="block text-xs font-semibold mb-1">Start</label><input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"/></div><div><label className="block text-xs font-semibold mb-1">End</label><input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"/></div><input type="number" min="1" value={capacity} onChange={e=>setCapacity(e.target.value)} placeholder="Capacity" className="w-full px-3 py-2 border rounded-lg bg-[#FAF9F6]"/>{error&&<p className="text-xs text-red-700">{error}</p>}<button className="w-full py-2.5 bg-[#141413] text-white rounded-lg text-xs font-semibold">Create Slot</button></form><section className="xl:col-span-7 bg-white border rounded-xl p-6"><h2 className="font-display font-bold mb-5">Configured Slots ({slots.length})</h2><div className="space-y-2">{slots.map(s=><div key={s.id} className="border rounded-lg p-4 flex items-center justify-between gap-4 text-xs"><div><p className="font-semibold">{services.find(x=>x.id===s.service_id)?.name||s.service_id}</p><p className="text-[#6E6E68]">{branches.find(x=>x.id===s.branch_id)?.name||s.branch_id} · {formatDate(s.start_time)} · {new Date(s.start_time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}–{new Date(s.end_time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</p><p className="text-[10px]">{s.is_available?'Available':'Unavailable'} · capacity {s.capacity}</p></div><button onClick={async()=>{if(!c)return;const r=await c.from('service_slots').update({is_available:!s.is_available}).eq('id',s.id);if(r.error)setError(r.error.message);else await load()}} className="font-semibold text-red-700">{s.is_available?'Disable':'Enable'}</button></div>)}</div></section></div></AdminShell>
}
