'use client';

import React,{useEffect,useState} from 'react';
import {AdminShell} from '@/components/admin/AdminShell';
import {createClient} from '@/lib/supabase/client';
import {slugify} from '@/lib/utils/format';

type Make={id:string;name:string;slug:string;logo_url:string|null;is_active:boolean};
type Model={id:string;make_id:string;name:string;slug:string;is_active:boolean};
type Variant={id:string;model_id:string;name:string|null;year_from:number|null;year_to:number|null;engine:string|null;engine_code:string|null;transmission:string|null;fuel_type:string|null;body_type:string|null;drive_type:string|null;is_active:boolean};

export default function AdminVehiclesPage(){
 const c=createClient();const [makes,setMakes]=useState<Make[]>([]);const [models,setModels]=useState<Model[]>([]);const [variants,setVariants]=useState<Variant[]>([]);const [makeId,setMakeId]=useState('');const [modelId,setModelId]=useState('');const [makeName,setMakeName]=useState('');const [modelName,setModelName]=useState('');const [variantName,setVariantName]=useState('');const [yearFrom,setYearFrom]=useState('');const [yearTo,setYearTo]=useState('');const [engine,setEngine]=useState('');const [error,setError]=useState('');
 const load=async()=>{if(!c)return;const [a,b,d]=await Promise.all([c.from('vehicle_makes').select('*').order('name'),c.from('vehicle_models').select('*').order('name'),c.from('vehicle_variants').select('*').order('name')]);if(a.error||b.error||d.error)setError(a.error?.message||b.error?.message||d.error?.message||'Unable to load vehicles');else{setMakes((a.data||[]) as Make[]);setModels((b.data||[]) as Model[]);setVariants((d.data||[]) as Variant[])}};useEffect(()=>{void load()},[]);
 const addMake=async(e:React.FormEvent)=>{e.preventDefault();if(!c||!makeName.trim())return;const r=await c.from('vehicle_makes').insert({name:makeName.trim(),slug:slugify(makeName),is_active:true});if(r.error)setError(r.error.message);else{setMakeName('');await load()}};const addModel=async(e:React.FormEvent)=>{e.preventDefault();if(!c||!makeId||!modelName.trim())return;const r=await c.from('vehicle_models').insert({make_id:makeId,name:modelName.trim(),slug:slugify(modelName),is_active:true});if(r.error)setError(r.error.message);else{setModelName('');await load()}};const addVariant=async(e:React.FormEvent)=>{e.preventDefault();if(!c||!modelId)return;const r=await c.from('vehicle_variants').insert({model_id:modelId,name:variantName.trim()||null,year_from:yearFrom?Number(yearFrom):null,year_to:yearTo?Number(yearTo):null,engine:engine.trim()||null,is_active:true});if(r.error)setError(r.error.message);else{setVariantName('');setYearFrom('');setYearTo('');setEngine('');await load()}};const toggle=async(table:string,id:string,active:boolean)=>{if(!c)return;const r=await c.from(table).update({is_active:!active}).eq('id',id);if(r.error)setError(r.error.message);else await load()};
 return <AdminShell title="Vehicle Fitment Database" subtitle="Manage make → model → variant data used for customer vehicles and part compatibility.">
 <div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><form onSubmit={addMake} className="bg-white border border-[#E5E5E0] rounded-xl p-5 space-y-3"><h2 className="font-display font-bold">Vehicle Makes</h2><input value={makeName} onChange={e=>setMakeName(e.target.value)} placeholder="e.g. Toyota" className="w-full px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"/><button className="w-full py-2.5 bg-[#141413] text-white rounded-lg text-xs font-semibold">Add Make</button><div className="space-y-2 max-h-80 overflow-auto">{makes.map(m=><div key={m.id} className="flex justify-between text-xs border-t pt-2"><span>{m.name}</span><button type="button" onClick={()=>void toggle('vehicle_makes',m.id,m.is_active)} className="text-red-700">{m.is_active?'Deactivate':'Activate'}</button></div>)}</div></form>
 <form onSubmit={addModel} className="bg-white border border-[#E5E5E0] rounded-xl p-5 space-y-3"><h2 className="font-display font-bold">Vehicle Models</h2><select required value={makeId} onChange={e=>setMakeId(e.target.value)} className="w-full px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"><option value="">Choose make</option>{makes.filter(x=>x.is_active).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select><input value={modelName} onChange={e=>setModelName(e.target.value)} placeholder="Model name" className="w-full px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"/><button className="w-full py-2.5 bg-[#141413] text-white rounded-lg text-xs font-semibold">Add Model</button><div className="space-y-2 max-h-80 overflow-auto">{models.map(m=><div key={m.id} className="text-xs border-t pt-2 flex justify-between"><span>{makes.find(x=>x.id===m.make_id)?.name} {m.name}</span><button type="button" onClick={()=>void toggle('vehicle_models',m.id,m.is_active)} className="text-red-700">{m.is_active?'Deactivate':'Activate'}</button></div>)}</div></form>
 <form onSubmit={addVariant} className="bg-white border border-[#E5E5E0] rounded-xl p-5 space-y-3"><h2 className="font-display font-bold">Vehicle Variants</h2><select required value={modelId} onChange={e=>setModelId(e.target.value)} className="w-full px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"><option value="">Choose model</option>{models.filter(x=>x.is_active).map(m=><option key={m.id} value={m.id}>{makes.find(x=>x.id===m.make_id)?.name} · {m.name}</option>)}</select><input value={variantName} onChange={e=>setVariantName(e.target.value)} placeholder="Variant / trim (optional)" className="w-full px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"/><div className="grid grid-cols-2 gap-2"><input value={yearFrom} onChange={e=>setYearFrom(e.target.value)} placeholder="Year from" type="number" className="px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"/><input value={yearTo} onChange={e=>setYearTo(e.target.value)} placeholder="Year to" type="number" className="px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"/></div><input value={engine} onChange={e=>setEngine(e.target.value)} placeholder="Engine / engine code" className="w-full px-3 py-2 text-sm border rounded-lg bg-[#FAF9F6]"/><button className="w-full py-2.5 bg-[#141413] text-white rounded-lg text-xs font-semibold">Add Variant</button><div className="space-y-2 max-h-80 overflow-auto">{variants.map(v=><div key={v.id} className="text-xs border-t pt-2 flex justify-between"><span>{models.find(x=>x.id===v.model_id)?.name} · {v.name||'Base variant'} · {v.year_from||''}{v.year_to?'-'+v.year_to:''}</span><button type="button" onClick={()=>void toggle('vehicle_variants',v.id,v.is_active)} className="text-red-700">{v.is_active?'Deactivate':'Activate'}</button></div>)}</div></form></div>{error&&<p className="mt-5 text-xs text-red-700">{error}</p>}</AdminShell>
}
