import {
  AutomotiveService,
  Brand,
  Category,
  Order,
  PartProduct,
  ServiceBooking,
  UserProfile,
  VlogPost,
} from '@/types/database';

export const INITIAL_BRANDS: Brand[] = [
  {
    id: 'brand-brembo',
    name: 'Brembo',
    slug: 'brembo',
    country: 'Italy',
    specialty: 'High-Carbon Brake Discs, Ceramic Brake Pads & Calipers',
    warranty_policy: '1-Year / 20,000 km Official Distributor Warranty',
    description:
      'World leader in braking systems. Every Brembo rotor and pad set features UV anti-corrosion coating and OE-equivalent friction compounds.',
  },
  {
    id: 'brand-motul',
    name: 'Motul',
    slug: 'motul',
    country: 'France',
    specialty: '100% Ester-Core Synthetic Motor Oils, ATF & Brake Fluids',
    warranty_policy: 'Guaranteed Authentic Sealed Batch Number',
    description:
      'Formulated in France for high-temperature turbo-diesel and high-revving gasoline engines operating in tropical stop-and-go traffic.',
  },
  {
    id: 'brand-denso',
    name: 'Denso',
    slug: 'denso',
    country: 'Japan',
    specialty: 'OEM Oil Filters, Cabin A/C Filters, Alternators & Compressors',
    warranty_policy: '6-Month OEM Replacement Guarantee',
    description:
      'First-fit original equipment supplier for Toyota, Honda, Mitsubishi, and Isuzu across Southeast Asia.',
  },
  {
    id: 'brand-bosch',
    name: 'Bosch',
    slug: 'bosch',
    country: 'Germany',
    specialty: 'AGM Maintenance-Free Batteries, Alternators, Wipers & Sensors',
    warranty_policy: '21-Month Nationwide Battery Replacement Warranty',
    description:
      'German-engineered automotive electrical systems, AGM start-stop batteries, and precision fuel-injection sensors.',
  },
  {
    id: 'brand-bilstein',
    name: 'Bilstein',
    slug: 'bilstein',
    country: 'Germany',
    specialty: 'Monotube Gas Shock Absorbers & Lift/Coilover Kits',
    warranty_policy: '2-Year Limited Damper Seal Warranty',
    description:
      'Gas-pressure monotube dampers engineered to eliminate body roll and nose-dive on SUVs, pickups, and sport sedans.',
  },
  {
    id: 'brand-ngk',
    name: 'NGK Ignition',
    slug: 'ngk',
    country: 'Japan',
    specialty: 'Laser Iridium Spark Plugs & Direct Ignition Coil Packs',
    warranty_policy: '100,000 km Service Interval Rated',
    description:
      'Ultra-fine 0.6mm laser-welded iridium center electrodes for crisp throttle response, cold-start reliability, and fuel economy.',
  },
];

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-brakes',
    name: 'Brakes, Rotors & Pads',
    slug: 'brakes',
    common_parts: 'Ceramic brake pads, slotted brake discs, DOT 4/5.1 brake fluid, caliper hardware',
    description:
      'OE-replacement and performance brake pads, high-carbon vented rotors, and braided brake lines.',
  },
  {
    id: 'cat-filters-oil',
    name: 'Engine Oil & Filters',
    slug: 'engine-filters',
    common_parts: 'Oil filters, air filters, cabin A/C filters, fuel filters, 5W-30 / 5W-40 synthetic oil',
    description:
      'Complete Periodic Maintenance Service (PMS) filter bundles and 100% synthetic motor oils.',
  },
  {
    id: 'cat-batteries',
    name: 'Batteries & Electrical',
    slug: 'batteries-electrical',
    common_parts: 'AGM & SMF car batteries, alternators, starter motors, relays, fuses',
    description:
      'Maintenance-free DIN and JIS automotive batteries with high Cold Cranking Amps (CCA) for tropical heat.',
  },
  {
    id: 'cat-suspension',
    name: 'Suspension & Steering',
    slug: 'suspension-steering',
    common_parts: 'Shock absorbers, coilovers, upper control arms, stabilizer links, tie rod ends',
    description:
      'Heavy-duty monotube shock absorbers, polyurethane bushings, and chassis refresh components.',
  },
  {
    id: 'cat-ignition',
    name: 'Ignition & Engine Parts',
    slug: 'ignition',
    common_parts: 'Iridium spark plugs, ignition coils, serpentine drive belts, radiator hoses, thermostats',
    description:
      'Genuine Japanese and German ignition coils, laser iridium spark plugs, and EPDM cooling hoses.',
  },
];

export const INITIAL_PARTS: PartProduct[] = [
  {
    id: 'part-1',
    slug: 'brembo-xtra-ceramic-front-brake-pad-rotor-kit-hilux-fortuner',
    sku: 'BRM-KT-09C401',
    name: 'Brembo Xtra Drilled/Slotted Front Brake Disc & Low-Met Ceramic Pad Kit',
    brand_id: 'brand-brembo',
    brand_name: 'Brembo',
    brand_slug: 'brembo',
    category_id: 'cat-brakes',
    category_name: 'Brakes, Rotors & Pads',
    category_slug: 'brakes',
    price: 16850,
    compare_at_price: 19200,
    stock: 14,
    status: 'Active',
    rating: 4.9,
    review_count: 86,
    is_featured: true,
    primary_image: '/images/part_brake_kit.jpg',
    gallery_images: [
      '/images/part_brake_kit.jpg',
      '/images/hero_parts_workshop.jpg',
    ],
    description:
      'Direct bolt-on front braking upgrade for Toyota Fortuner, Hilux, and Innova platforms. Combines Brembo High-Carbon UV-coated cross-drilled & slotted 338mm vented discs with low-dust, zero-squeal Brembo Ceramic friction pads. Eliminates highway brake fade even under full 7-passenger load or steep mountain descents.',
    specifications: {
      'Part Number (SKU)': 'BRM-KT-09C401',
      'Axle Position': 'Front Axle (Left & Right Pair + 4 Pads)',
      'Rotor Diameter': '338 mm x 28 mm Vented High-Carbon',
      'Surface Finish': 'UV Anti-Corrosion Coated / Slotted & Drilled',
      'Pad Compound': 'Brembo NAO Ceramic (Low Dust + Wear Sensor Clip)',
      'Box Weight': '21.4 kg',
    },
    compatibility: [
      { make: 'Toyota', model: 'Fortuner (AN150 / AN160)', years: '2016–2026', engine: '2.4L 2GD / 2.8L 1GD Diesel' },
      { make: 'Toyota', model: 'Hilux Conquest / GR-S', years: '2016–2026', engine: '2.4L / 2.8L Turbo Diesel' },
      { make: 'Toyota', model: 'Innova', years: '2016–2024', engine: '2.8L 1GD-FTV Diesel' },
    ],
    vlog_episode_slug: 'ep-43-brembo-brake-upgrade-and-runout-test',
    created_at: '2026-09-28T08:00:00Z',
  },
  {
    id: 'part-2',
    slug: 'motul-8100-xclean-5w30-synthetic-pms-bundle-denso-filters',
    sku: 'MTL-PMS-8100-7L',
    name: 'Motul 8100 X-Clean+ 5W-30 100% Synthetic (7L) + Denso OEM Oil & Air Filter PMS Kit',
    brand_id: 'brand-motul',
    brand_name: 'Motul',
    brand_slug: 'motul',
    category_id: 'cat-filters-oil',
    category_name: 'Engine Oil & Filters',
    category_slug: 'engine-filters',
    price: 5450,
    compare_at_price: 6200,
    stock: 38,
    status: 'Active',
    rating: 5.0,
    review_count: 142,
    is_featured: true,
    primary_image: '/images/part_oil_filter_kit.jpg',
    gallery_images: [
      '/images/part_oil_filter_kit.jpg',
      '/images/hero_parts_workshop.jpg',
    ],
    description:
      'Complete 10,000 km Periodic Maintenance Service (PMS) package containing 7 Liters of French-made Motul 8100 X-Clean+ 5W-30 ACEA C3 100% Synthetic motor oil, a genuine Denso heavy-duty oil filter element with O-ring, a Denso pleated engine air filter, and a copper drain plug crush washer.',
    specifications: {
      'Part Number (SKU)': 'MTL-PMS-8100-7L',
      'Viscosity Grade': 'SAE 5W-30 (100% Full Synthetic)',
      'API / ACEA Spec': 'ACEA C3 / API SP (DPF & Turbo Safe)',
      'Total Oil Volume': '7 Liters (1x 5L Jug + 2x 1L Bottles)',
      'Included Filters': 'Denso Oil Filter + Denso Engine Air Filter + Drain Washer',
      'Service Interval': 'Up to 10,000 km or 6 Months',
    },
    compatibility: [
      { make: 'Toyota', model: 'Fortuner / Hilux / Prado', years: '2016–2026', engine: '2.4L 2GD / 2.8L 1GD' },
      { make: 'Mitsubishi', model: 'Montero Sport (Gen 3/3.5)', years: '2016–2026', engine: '2.4L 4N15 MIVEC Turbo Diesel' },
      { make: 'Ford', model: 'Ranger / Everest', years: '2018–2026', engine: '2.0L Bi-Turbo / Single-Turbo Diesel' },
    ],
    vlog_episode_slug: 'ep-42-10000km-oil-analysis-motul-vs-mineral-oil',
    created_at: '2026-09-29T10:15:00Z',
  },
  {
    id: 'part-3',
    slug: 'bosch-s6-agm-din80-start-stop-automotive-battery-800cca',
    sku: 'BSH-S6-AGM-LN4',
    name: 'Bosch S6 High-Performance AGM DIN80 (LN4) Maintenance-Free Car Battery — 800 CCA',
    brand_id: 'brand-bosch',
    brand_name: 'Bosch',
    brand_slug: 'bosch',
    category_id: 'cat-batteries',
    category_name: 'Batteries & Electrical',
    category_slug: 'batteries-electrical',
    price: 11900,
    compare_at_price: 13500,
    stock: 19,
    status: 'Active',
    rating: 4.8,
    review_count: 64,
    is_featured: true,
    primary_image: '/images/part_agm_battery.jpg',
    gallery_images: [
      '/images/part_agm_battery.jpg',
      '/images/hero_parts_workshop.jpg',
    ],
    description:
      'Absorbent Glass Mat (AGM) technology engineered by Bosch for modern vehicles with high electrical loads, dashcams, and Auto Start-Stop systems. Delivers 3x the cycle life of conventional flooded batteries and 800 Cold Cranking Amps (CCA) with zero acid spills.',
    specifications: {
      'Part Number (SKU)': 'BSH-S6-AGM-LN4',
      'Battery Size Code': 'DIN80 / LN4 (315 x 175 x 190 mm)',
      'Capacity (20hr)': '80 Ah',
      'Cold Cranking Amps': '800 CCA (EN)',
      'Terminal Layout': 'Standard Euro Post (Right Positive)',
      'Warranty': '21 Months Official Bosch PH Replacement Warranty',
    },
    compatibility: [
      { make: 'Ford', model: 'Ranger Raptor / Wildtrak / Everest', years: '2016–2026', engine: '2.0L Bi-Turbo / 3.0L V6' },
      { make: 'BMW', model: '3 Series (G20) / X3 (G01)', years: '2019–2025', engine: '2.0L B48 / B47' },
      { make: 'Toyota', model: 'Hilux / Fortuner (Euro DIN Tray)', years: '2020–2026', engine: '2.8L 1GD-FTV' },
    ],
    created_at: '2026-09-30T11:30:00Z',
  },
  {
    id: 'part-4',
    slug: 'bilstein-b6-4600-monotube-gas-shock-absorber-set-of-4',
    sku: 'BIL-24-263108-SET',
    name: 'Bilstein B6 4600 Heavy-Duty Monotube Gas Shock Absorber Set (Front & Rear 4-Pc Kit)',
    brand_id: 'brand-bilstein',
    brand_name: 'Bilstein',
    brand_slug: 'bilstein',
    category_id: 'cat-suspension',
    category_name: 'Suspension & Steering',
    category_slug: 'suspension-steering',
    price: 34500,
    compare_at_price: 38900,
    stock: 8,
    status: 'Active',
    rating: 4.9,
    review_count: 51,
    is_featured: true,
    primary_image: '/images/part_suspension_coilover.jpg',
    gallery_images: [
      '/images/part_suspension_coilover.jpg',
      '/images/hero_parts_workshop.jpg',
    ],
    description:
      'Made in Germany. The Bilstein B6 4600 46mm monotube gas-pressure damper set transforms harsh, bouncy factory SUV and pickup suspension into composed European-style highway stability. Works with factory standard height coil springs—no lift modification required.',
    specifications: {
      'Part Number (SKU)': 'BIL-24-263108-SET',
      'Damper Design': '46mm Digressive Piston High-Pressure Monotube Gas',
      'Kit Contents': '2x Front Strut Dampers + 2x Rear Shock Absorbers + Bushings',
      'Ride Height': 'compatible with Stock 0" to +1" Standard Springs',
      'Country of Manufacture': 'Germany',
    },
    compatibility: [
      { make: 'Toyota', model: 'Fortuner (Gen 2 / facelift)', years: '2016–2026', engine: 'All 4x2 & 4x4 Variants' },
      { make: 'Mitsubishi', model: 'Montero Sport', years: '2016–2026', engine: '2.4L 4N15' },
      { make: 'Nissan', model: 'Terra / Navara', years: '2018–2026', engine: '2.5L YD25' },
    ],
    vlog_episode_slug: 'ep-41-fixing-suv-body-roll-bilstein-b6-install',
    created_at: '2026-10-01T09:00:00Z',
  },
  {
    id: 'part-5',
    slug: 'ngk-laser-iridium-spark-plugs-set-of-4-dilkar7g11gs',
    sku: 'NGK-91578-4PK',
    name: 'NGK Laser Iridium Spark Plugs (Set of 4) — High-Ignitability 0.6mm Fine Tip',
    brand_id: 'brand-ngk',
    brand_name: 'NGK Ignition',
    brand_slug: 'ngk',
    category_id: 'cat-ignition',
    category_name: 'Ignition & Engine Parts',
    category_slug: 'ignition',
    price: 3680,
    compare_at_price: 4200,
    stock: 45,
    status: 'Active',
    rating: 4.9,
    review_count: 119,
    is_featured: true,
    primary_image: '/images/part_spark_plugs_ignition.jpg',
    gallery_images: [
      '/images/part_spark_plugs_ignition.jpg',
      '/images/hero_parts_workshop.jpg',
    ],
    description:
      'Genuine Japanese NGK Laser Iridium spark plugs featuring a laser-welded 0.6mm iridium center electrode tip and platinum ground electrode disc. Restores crisp throttle response, eliminates rough idle misfires, and improves fuel efficiency.',
    specifications: {
      'Part Number (SKU)': 'NGK-91578-4PK',
      'Quantity': 'Box of 4 Pre-Gapped Spark Plugs',
      'Electrode Material': 'Laser-Welded Iridium Center + Platinum Ground Tip',
      'Hex Size / Thread': '14mm Hex / 12mm Thread Reach 26.5mm',
      'Heat Range': '7 (Turbo & High-Compression Safe)',
    },
    compatibility: [
      { make: 'Honda', model: 'Civic FC / FE / CR-V', years: '2016–2026', engine: '1.5L VTEC Turbo / 1.8L i-VTEC' },
      { make: 'Toyota', model: 'Corolla Altis / Camry / RAV4', years: '2014–2026', engine: '1.6L / 1.8L / 2.0L Dual VVT-i' },
      { make: 'Mazda', model: 'Mazda3 / CX-5 / CX-30', years: '2015–2026', engine: '2.0L / 2.5L Skyactiv-G' },
    ],
    created_at: '2026-10-02T14:00:00Z',
  },
  {
    id: 'part-6',
    slug: 'denso-clean-air-activated-carbon-cabin-ac-filter-heavy-duty',
    sku: 'DNS-DCC1009-CB',
    name: 'Denso Clean-Air 5-Layer Activated Carbon & Anti-Viral Cabin A/C Filter',
    brand_id: 'brand-denso',
    brand_name: 'Denso',
    brand_slug: 'denso',
    category_id: 'cat-filters-oil',
    category_name: 'Engine Oil & Filters',
    category_slug: 'engine-filters',
    price: 1150,
    compare_at_price: 1450,
    stock: 62,
    status: 'Active',
    rating: 4.8,
    review_count: 94,
    is_featured: true,
    primary_image: '/images/part_oil_filter_kit.jpg',
    gallery_images: ['/images/part_oil_filter_kit.jpg'],
    description:
      'Upgraded 5-layer Denso Clean-Air cabin filter impregnated with coconut-shell activated carbon and PM2.5 electrostatic media. Blocks diesel exhaust fumes, pollen, and musty evaporator odors inside your cabin.',
    specifications: {
      'Part Number (SKU)': 'DNS-DCC1009-CB',
      'Filtration Media': 'PM2.5 Electrostatic + Activated Carbon Layer',
      'Dimensions': '215 mm x 194 mm x 29 mm',
      'Recommended Replacement': 'Every 10,000 km or 6 Months',
    },
    compatibility: [
      { make: 'Toyota', model: 'Vios / Yaris / Raize / Veloz', years: '2014–2026', engine: '1.3L / 1.5L / 1.0L Turbo' },
      { make: 'Toyota', model: 'Fortuner / Hilux / Innova / Corolla Cross', years: '2016–2026', engine: 'All Variants' },
      { make: 'Subaru', model: 'Forester / XV / Crosstrek', years: '2018–2025', engine: '2.0L Boxer' },
    ],
    created_at: '2026-10-03T11:00:00Z',
  },
];

export const INITIAL_SERVICES: AutomotiveService[] = [
  {
    id: 'srv-1',
    slug: 'full-synthetic-pms-oil-filter-change-28-point-check',
    service_code: 'SRV-PMS-10K',
    name: 'Complete 10,000 km Periodic Maintenance Service (Full Synthetic Oil + Filters + 28-Point Check)',
    category: 'Periodic Maintenance',
    price: 6200,
    duration_minutes: 60,
    duration_label: '60 Minutes (While-You-Wait Lounge)',
    availability: 'Available',
    description:
      'Comprehensive CASA-grade Periodic Maintenance Service performed on our two-post hydraulic lift. Includes draining old engine oil, installing a genuine OEM oil filter, pouring up to 7L of 100% synthetic motor oil, cleaning/replacing air and cabin filters, rotating tires, and running a full OBD-II computer diagnostic scan.',
    included_operations: [
      'Up to 7 Liters 100% Synthetic Motor Oil (5W-30 or 5W-40) + OEM Oil Filter',
      'New Copper Drain Plug Washer & Torque-Wrench Spec Tightening',
      'Brake Pad Thickness Measurement & Caliper Slide-Pin Cleaning',
      'Battery CCA Load Test & Alternator Charging Voltage Check',
      'OBD-II All-Module Fault Code Scan & Service Reminder Reset',
    ],
    recommended_interval: 'Every 10,000 km or 6 Months',
    image_url: '/images/part_oil_filter_kit.jpg',
  },
  {
    id: 'srv-2',
    slug: 'precision-brake-pad-replacement-and-rotor-resurfacing',
    service_code: 'SRV-BRK-PRO',
    name: 'Front or Rear Brake Pad Installation, Rotor Runout Resurfacing & DOT 4 Fluid Bleed',
    category: 'Brakes & Chassis',
    price: 2800,
    duration_minutes: 90,
    duration_label: '90 Minutes',
    availability: 'Available',
    description:
      'Eliminate brake pedal vibration, squealing, and spongy pedal feel. Our technicians clean the wheel hub face to zero rust, measure lateral disc runout with a dial gauge, lubricate caliper guide pins with high-temp silicone grease, install your new brake pads/rotors, and pressure-bleed the hydraulic system.',
    included_operations: [
      'Precision On-Lathe Rotor Resurfacing or New Rotor Installation',
      'Dial-Indicator Hub & Disc Runout Verification (< 0.04mm)',
      'Caliper Piston Boot Inspection & Guide Pin Synthetic Lubrication',
      'Complete 4-Wheel Pressure Brake Fluid Flush (DOT 4)',
    ],
    recommended_interval: 'Every 20,000 km or when pads reach 3mm',
    image_url: '/images/part_brake_kit.jpg',
  },
  {
    id: 'srv-3',
    slug: 'agm-battery-installation-bms-coding-alternator-test',
    service_code: 'SRV-BAT-BMS',
    name: 'Battery Replacement, Memory Saver Backup, BMS Registration & Charging System Test',
    category: 'Electrical & Battery',
    price: 950,
    duration_minutes: 30,
    duration_label: '30 Minutes (Free labor when buying battery from us)',
    availability: 'Available',
    description:
      'Modern vehicles require OB-II memory preservation and Battery Management System (BMS) reset when installing a new battery so the smart alternator does not overcharge the new cells. We keep your ECU/radio settings alive during swap and register the new AGM/SMF battery capacity.',
    included_operations: [
      'OBD-II 12V Memory Keeper Connection During Battery Swap',
      'Battery Terminal Anti-Corrosion Cleaning & Dielectric Protection',
      'BMS (Battery Management System) Computer Registration via Scanner',
      'Starter Cranking Voltage Drop & Alternator Ripple Test Printout',
    ],
    recommended_interval: 'Every 18–24 Months',
    image_url: '/images/part_agm_battery.jpg',
  },
  {
    id: 'srv-4',
    slug: 'suspension-shock-absorber-installation-3d-wheel-alignment',
    service_code: 'SRV-SUS-3D',
    name: 'Shock Absorber / Coilover Installation + Computerized 4-Wheel 3D Laser Alignment',
    category: 'Tires & Alignment',
    price: 4500,
    duration_minutes: 120,
    duration_label: '2 Hours',
    availability: 'Available',
    description:
      'Complete installation of front struts and rear shock absorbers or coilovers, followed by bushing preload torquing at ride height and a computerized 4-wheel camber, caster, and toe laser alignment.',
    included_operations: [
      'Front Strut Spring Compression & Top-Mount Bearing Inspection',
      'Ride-Height Bushing Preload Torquing (Prevents Bushing Tear)',
      'Computerized 3D 4-Wheel Camber, Caster & Toe Laser Alignment',
      'Road-Test & Steering Wheel Center Verification',
    ],
    recommended_interval: 'Every 40,000 km or after suspension work',
    image_url: '/images/part_suspension_coilover.jpg',
  },
  {
    id: 'srv-5',
    slug: 'obd2-computer-diagnostics-and-dual-zone-ac-service',
    service_code: 'SRV-DIAG-AC',
    name: 'Full-System OBD-II Diagnostics, Injector Data Live Stream & A/C Refrigerant Recharge',
    category: 'Diagnostics & A/C',
    price: 3200,
    duration_minutes: 75,
    duration_label: '75 Minutes',
    availability: 'Available',
    description:
      'Pinpoint check-engine lights, ABS/airbag faults, turbo boost leaks, or weak air-conditioning cooling. Includes live fuel-injector correction reading and automated R134a / R1234yf A/C refrigerant recovery, vacuum leak test, compressor oil replenishment, and recharge.',
    included_operations: [
      'Full OEM-Level Bi-Directional Diagnostic Scanner Report',
      'Common-Rail Diesel Injector Pilot & Feedback Value Check',
      'Automated A/C System Vacuum Leak Test & Pure Freon Recharge',
      'Cabin Vent Temperature & High/Low Side Pressure Verification',
    ],
    recommended_interval: 'Annually or when warning lights / warm A/C occur',
    image_url: '/images/part_spark_plugs_ignition.jpg',
  },
];

export const INITIAL_VLOGS: VlogPost[] = [
  {
    id: 'vlog-1',
    slug: 'ep-43-brembo-brake-upgrade-and-runout-test',
    episode_number: 43,
    title: 'Daily Workshop Vlog #43: Why New Brake Rotors Warp & Installing Brembo Xtra Ceramic Brakes on a Fortuner',
    published_at: '2026-10-04',
    duration: '16:24',
    author_name: 'Marco Villanueva',
    author_role: 'Master Technician & Founder',
    category: 'Part Install Guide',
    summary:
      'In today’s morning service bay vlog, we show you why skipping hub-face rust cleaning causes steering wheel shudder at 100 km/h—and install our Brembo Xtra Drilled/Slotted Front Kit.',
    content: [
      'Welcome back to the Apex Auto Parts & Service Bay daily vlog! First customer on the hoist at 8:00 AM today is a 2022 Toyota Fortuner 2.8 LTD whose owner complained of violent steering wheel shaking whenever braking downhill on Skyway ramps.',
      'Before bolting on the new Brembo Xtra 338mm UV-coated rotors and ceramic pads from our parts counter, we wire-brush the wheel hub mounting surface and use our magnetic dial indicator to verify lateral runout is under 0.02mm.',
      'You can order this exact Brembo kit online with nationwide shipping, or book our 90-minute Brake Service bay directly on the site!',
    ],
    thumbnail_url: '/images/part_brake_kit.jpg',
    video_highlights: [
      { timestamp: '00:00', label: 'Measuring warped stock rotor runout on the dial gauge' },
      { timestamp: '04:40', label: 'Unboxing the Brembo Xtra Rotor & Ceramic Pad Kit (BRM-KT-09C401)' },
      { timestamp: '09:15', label: 'Hub face prep, silicone pin grease & torque wrench spec' },
      { timestamp: '13:50', label: 'Bedding-in road test & thermal camera temperature check' },
    ],
    featured_part_slug: 'brembo-xtra-ceramic-front-brake-pad-rotor-kit-hilux-fortuner',
    featured_part_name: 'Brembo Xtra Front Brake Disc & Ceramic Pad Kit',
    featured_part_price: 16850,
    featured_service_slug: 'precision-brake-pad-replacement-and-rotor-resurfacing',
    views_count: 18420,
    likes_count: 1540,
    comments: [
      {
        id: 'c-1',
        user_name: 'Carlo Mendoza',
        created_at: '2026-10-04T11:20:00Z',
        text: 'Ordered this exact Brembo kit from your parts store last week and had you guys install it on Saturday. Zero brake dust and stops on a dime!',
      },
    ],
  },
  {
    id: 'vlog-2',
    slug: 'ep-42-10000km-oil-analysis-motul-vs-mineral-oil',
    episode_number: 42,
    title: 'Daily Workshop Vlog #42: Cutting Open a 10,000 km Oil Filter & Motul 8100 5W-30 Full PMS Walkthrough',
    published_at: '2026-10-03',
    duration: '14:10',
    author_name: 'Marco Villanueva',
    author_role: 'Master Technician & Founder',
    category: 'Service Bay Vlog',
    summary:
      'We cut open two used oil filters on our workbench—one run on cheap mineral oil and one run on Motul 8100 X-Clean+ 100% Synthetic—to show you what carbon sludge looks like inside a turbo diesel.',
    content: [
      'Every day in our service bay, we perform 8 to 10 Periodic Maintenance Services (PMS). Today we put our filter cutter to work so you can see why genuine Denso pleat density and 100% synthetic ACEA C3 oil matter for modern turbochargers.',
      'We also walk through every step of our 60-minute ₱6,200 PMS package, including battery CCA load testing and resetting the maintenance interval via OBD-II.',
    ],
    thumbnail_url: '/images/part_oil_filter_kit.jpg',
    video_highlights: [
      { timestamp: '00:00', label: 'Cutting open a 10,000 km Denso filter on the bench' },
      { timestamp: '05:10', label: 'Why turbo-diesels need ACEA C3 low-SAPS synthetic oil' },
      { timestamp: '10:05', label: '28-point underchassis check on the two-post hoist' },
    ],
    featured_part_slug: 'motul-8100-xclean-5w30-synthetic-pms-bundle-denso-filters',
    featured_part_name: 'Motul 8100 X-Clean+ 5W-30 (7L) + Denso Filter PMS Kit',
    featured_part_price: 5450,
    featured_service_slug: 'full-synthetic-pms-oil-filter-change-28-point-check',
    views_count: 12390,
    likes_count: 980,
    comments: [],
  },
  {
    id: 'vlog-3',
    slug: 'ep-41-fixing-suv-body-roll-bilstein-b6-install',
    episode_number: 41,
    title: 'Daily Workshop Vlog #41: Curing SUV Boat-Like Body Roll with German Bilstein B6 Monotube Shocks',
    published_at: '2026-10-02',
    duration: '19:05',
    author_name: 'Gabby Lorenzo',
    author_role: 'Lead Suspension Specialist',
    category: 'Part Install Guide',
    summary:
      'Why you must pre-load rubber control arm bushings at ride height before torquing bolts—plus a before-and-after highway lane-change test on Bilstein B6 4600 shocks.',
    content: [
      'One of the biggest mistakes shops make when installing new shock absorbers is tightening the control arm and shock eye bolts while the wheels are hanging in the air on a two-post lift. That twists the rubber bushing at rest and tears it within 5,000 km.',
      'In Episode 41, Gabby demonstrates how we use our 4-post alignment rack to torque every suspension bolt at true static ride height after installing a 4-piece Bilstein B6 4600 monotube kit.',
    ],
    thumbnail_url: '/images/part_suspension_coilover.jpg',
    video_highlights: [
      { timestamp: '00:00', label: 'Stock twin-tube shock vs Bilstein 46mm monotube compression test' },
      { timestamp: '07:20', label: 'Proper ride-height bushing preload torquing procedure' },
      { timestamp: '14:15', label: '3D laser wheel alignment & highway stability test' },
    ],
    featured_part_slug: 'bilstein-b6-4600-monotube-gas-shock-absorber-set-of-4',
    featured_part_name: 'Bilstein B6 4600 Monotube Gas Shock Absorber Set (4-Pc)',
    featured_part_price: 34500,
    featured_service_slug: 'suspension-shock-absorber-installation-3d-wheel-alignment',
    views_count: 15100,
    likes_count: 1320,
    comments: [],
  },
];

export const INITIAL_SERVICE_BOOKINGS: ServiceBooking[] = [
  {
    id: 'sb-101',
    booking_reference: 'SRV-90421',
    service_id: 'srv-1',
    service_slug: 'full-synthetic-pms-oil-filter-change-28-point-check',
    service_name: 'Complete 10,000 km Periodic Maintenance Service (Full Synthetic Oil + Filters + 28-Point Check)',
    service_price: 6200,
    user_id: 'user-demo-1',
    customer_name: 'Miguel Santos',
    customer_email: 'miguel.santos@example.ph',
    customer_phone: '+63 917 555 0192',
    vehicle_details: '2021 Toyota Fortuner 2.8 LTD (40,000 km check)',
    preferred_date: '2026-10-08',
    preferred_time: '09:00 AM',
    notes: 'Please also check front brake pad thickness and wiper blades.',
    status: 'Confirmed',
    created_at: '2026-10-03T14:20:00Z',
  },
  {
    id: 'sb-102',
    booking_reference: 'SRV-90458',
    service_id: 'srv-2',
    service_slug: 'precision-brake-pad-replacement-and-rotor-resurfacing',
    service_name: 'Front or Rear Brake Pad Installation, Rotor Runout Resurfacing & DOT 4 Fluid Bleed',
    service_price: 2800,
    customer_name: 'Rafael Alcantara',
    customer_email: 'rafael.alcantara@example.ph',
    customer_phone: '+63 918 820 4411',
    vehicle_details: '2020 Honda Civic RS Turbo',
    preferred_date: '2026-10-09',
    preferred_time: '01:30 PM',
    notes: 'Installing Brembo pads purchased from your online store.',
    status: 'Pending',
    created_at: '2026-10-04T09:10:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1001',
    order_number: 'ORD-782410',
    user_id: 'user-demo-1',
    customer_name: 'Miguel Santos',
    customer_email: 'miguel.santos@example.ph',
    customer_phone: '+63 917 555 0192',
    shipping_address: '148 McKinley Parkway, Bonifacio Global City',
    shipping_city: 'Taguig City, Metro Manila',
    shipping_postal_code: '1634',
    payment_method: 'GCash',
    payment_status: 'Paid',
    fulfillment_status: 'Shipped',
    items: [
      {
        product_id: 'part-1',
        product_slug: 'brembo-xtra-ceramic-front-brake-pad-rotor-kit-hilux-fortuner',
        sku: 'BRM-KT-09C401',
        name: 'Brembo Xtra Drilled/Slotted Front Brake Disc & Low-Met Ceramic Pad Kit',
        brand_name: 'Brembo',
        unit_price: 16850,
        quantity: 1,
        subtotal: 16850,
        image: '/images/part_brake_kit.jpg',
      },
      {
        product_id: 'part-6',
        product_slug: 'denso-clean-air-activated-carbon-cabin-ac-filter-heavy-duty',
        sku: 'DNS-DCC1009-CB',
        name: 'Denso Clean-Air 5-Layer Activated Carbon & Anti-Viral Cabin A/C Filter',
        brand_name: 'Denso',
        unit_price: 1150,
        quantity: 2,
        subtotal: 2300,
        image: '/images/part_oil_filter_kit.jpg',
      },
    ],
    subtotal: 19150,
    shipping_fee: 0,
    discount_amount: 0,
    total_amount: 19150,
    notes: 'Leave with building concierge if out.',
    created_at: '2026-10-03T16:10:00Z',
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-demo-1',
    name: 'Miguel Santos',
    email: 'miguel.santos@example.ph',
    phone: '+63 917 555 0192',
    address: '148 McKinley Parkway, Bonifacio Global City',
    city: 'Taguig City, Metro Manila',
    postal_code: '1634',
    garage_vehicle: '2021 Toyota Fortuner 2.8 LTD',
    role: 'admin',
    created_at: '2026-01-15T08:00:00Z',
  },
];
